version: "3.7"

services:
  wikiless:
   build:
      context: .
      dockerfile: Dockerfile
    container_name: wikiless
    hostname: wikiless
    #image: ghcr.io/metastem/wikiless:latest
    restart: always
    networks:
      wikiless_net:
        ipv4_address: 172.4.0.6
    environment:
      REDIS_HOST: redis://172.4.0.5:6379
    ports:
      - "127.0.0.1:8180:8080"
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    depends_on:
        - wikiless-redis

  wikiless-redis:
    container_name: wikiless-redis
    hostname: wikiless-redis
    image: redis:latest
    restart: always
    networks:
      wikiless_net:
        ipv4_address: 172.4.0.5
    ports:
      - "6379"
    user: nobody
    read_only: true
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /data:size=10M,mode=0770,uid=65534,gid=65534,noexec,nosuid,nodev
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE

networks:
  wikiless_net:
    ipam:
      config:
        - subnet: 172.4.0.0/16
